language: node_js
node_js:
      - "8"
services:
  - redis-server
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS steemitgame;'
  - mysql -u root --default-character-set=utf8 steemitgame < test/steemitgame.sql
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('111111') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
notifications:
  email:
    recipients:
      - bizheng@gmail.com
      - bonjovis1985@gmail.com
      - 195643+bobdos@users.noreply.github.com
    on_success: always # default: change
    on_failure: always # default: always
